from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatMessage(BaseModel):
    """Represents a single message turn in the conversation history."""
    role: str = Field(..., description="Must be either 'user' or 'model' to match Gemini's API specs.")
    content: str = Field(..., description="The textual message content.")

class AgentInput(BaseModel):
    """The unified input payload passed down to any routed Agent."""
    student_id: str = Field(..., description="Unique identifier for tracking the student's profile.")
    session_id: str = Field(..., description="Tracks the active chat session.")
    current_input: str = Field(..., description="The latest question, math problem, or statement from the student.")
    active_history: List[ChatMessage] = Field(default_factory=list, description="The uncompressed active sliding window messages.")
    running_summary: Optional[str] = Field(default="", description="The compressed historical summary generated by the memory compactor.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extensible dictionary for fields like preferred_language, target_topic, etc.")

class AgentOutput(BaseModel):
    """The strict structured format every Agent is forced to return."""
    agent_name: str = Field(..., description="The name of the agent handling the request (e.g., 'DiagnosisAgent').")
    response_text: str = Field(..., description="The final text targeted directly at the student.")
    internal_analysis: str = Field(..., description="Hidden metadata evaluating student mistakes, sent to the long-term memory/Struggle Detector.")
    confidence_score: float = Field(..., description="A score between 0.0 and 1.0 indicating model certainty.")